/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CaixaDeDialogo: typeof import('./src/components/generic/CaixaDeDialogo.vue')['default']
    CampoCLAV: typeof import('./src/components/generic/CampoCLAV.vue')['default']
    ClassesArvore: typeof import('./src/components/classes/ClassesArvore.vue')['default']
    ConsultaClasse: typeof import('./src/components/classes/consulta/ConsultaClasse.vue')['default']
    Definicoes: typeof import('./src/components/principal/Definicoes.vue')['default']
    Info: typeof import('./src/components/principal/Info.vue')['default']
    InfoBox: typeof import('./src/components/generic/InfoBox.vue')['default']
    Legislacao: typeof import('./src/components/classes/consulta/Legislacao.vue')['default']
    Listagem: typeof import('./src/components/generic/Listagem.vue')['default']
    Loading: typeof import('./src/components/generic/Loading.vue')['default']
    MainPageHeader: typeof import('./src/components/MainPageHeader.vue')['default']
    Noticias: typeof import('./src/components/principal/Noticias.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PainelCLAV: typeof import('./src/components/generic/PainelCLAV.vue')['default']
    Participantes: typeof import('./src/components/classes/consulta/Participantes.vue')['default']
    ProcessosRelacionados: typeof import('./src/components/classes/consulta/ProcessosRelacionados.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelasSelecao: typeof import('./src/components/tabelasSelecao/TabelasSelecao.vue')['default']
    Voltar: typeof import('./src/components/generic/Voltar.vue')['default']
  }
}
