/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CaixaDeDialogo: typeof import('./src/components/generic/CaixaDeDialogo.vue')['default']
    ClassesArvoreLateral: typeof import('./src/components/classes/ClassesArvoreLateral.vue')['default']
    Definicoes: typeof import('./src/components/principal/Definicoes.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Info: typeof import('./src/components/principal/Info.vue')['default']
    Loading: typeof import('./src/components/generic/Loading.vue')['default']
    MainPageHeader: typeof import('./src/components/MainPageHeader.vue')['default']
    Noticias: typeof import('./src/components/principal/Noticias.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
